exports.up = async (knex) => {
  await knex.raw(`SET NAMES utf8mb4`)

  await knex.schema.createTableIfNotExists('admins', (t) => {
    t.increments('id').unsigned().primary()
    t.string('username', 50).notNullable().unique()
    t.string('password', 255).notNullable()
    t.string('name', 50).notNullable()
    t.string('email', 100).notNullable()
    t.tinyint('isActive').notNullable().defaultTo(1)
    t.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    t.datetime('updatedAt').notNullable().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
  })

  await knex.schema.createTableIfNotExists('admin_allowed_ips', (t) => {
    t.increments('id').unsigned().primary()
    t.string('ipAddress', 45).notNullable()
    t.string('memo', 100)
    t.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    t.unique(['ipAddress'], 'uq_ip')
  })

  await knex.schema.createTableIfNotExists('members', (t) => {
    t.increments('id').unsigned().primary()
    t.string('username', 50).notNullable().unique()
    t.string('password', 255).notNullable()
    t.string('name', 50).notNullable()
    t.string('email', 100).notNullable().unique()
    t.string('phone', 20)
    t.string('flexUsername', 100).comment('FlexTV 아이디')
    t.tinyint('status').notNullable().defaultTo(0).comment('0:정상 1:차단')
    t.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    t.datetime('updatedAt').notNullable().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
  })

  await knex.schema.createTableIfNotExists('password_reset_tokens', (t) => {
    t.increments('id').unsigned().primary()
    t.integer('memberId').unsigned().notNullable()
    t.string('token', 100).notNullable().unique()
    t.datetime('expiresAt').notNullable()
    t.datetime('usedAt')
    t.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    t.index(['memberId'], 'idx_memberId')
  })

  await knex.schema.createTableIfNotExists('products', (t) => {
    t.increments('id').unsigned().primary()
    t.string('category', 30).notNullable()
    t.string('subcategory', 30).notNullable()
    t.string('name', 100).notNullable()
    t.integer('price').unsigned().notNullable()
    t.integer('lexAmount').unsigned().notNullable().defaultTo(0)
    t.integer('coinAmount').unsigned().notNullable().defaultTo(0)
    t.tinyint('isActive').notNullable().defaultTo(1)
    t.integer('sort').notNullable().defaultTo(0)
    t.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    t.datetime('updatedAt').notNullable().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    t.index(['category', 'subcategory', 'isActive'], 'idx_category')
  })

  await knex.schema.createTableIfNotExists('orders', (t) => {
    t.increments('id').unsigned().primary()
    t.string('orderNo', 30).notNullable().unique()
    t.integer('memberId').unsigned().notNullable()
    t.integer('productId').unsigned().notNullable()
    t.string('productName', 100).notNullable()
    t.integer('price').unsigned().notNullable()
    t.string('flexUsername', 100)
    t.tinyint('paymentMethod').notNullable().defaultTo(1).comment('1:카드 2:계좌이체')
    t.tinyint('paymentStatus').notNullable().defaultTo(0).comment('0:대기 1:완료 2:취소')
    t.tinyint('chargeStatus').notNullable().defaultTo(0).comment('0:대기 1:완료 2:환불')
    t.string('pgTrxNo', 100)
    t.string('pgTid', 100)
    t.datetime('paidAt')
    t.datetime('chargedAt')
    t.string('ipAddr', 45)
    t.string('memo', 500)
    t.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    t.datetime('updatedAt').notNullable().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    t.index(['memberId'], 'idx_memberId')
    t.index(['orderNo'], 'idx_orderNo')
    t.index(['paymentStatus', 'chargeStatus'], 'idx_paymentStatus')
    t.index(['createdAt'], 'idx_createdAt')
  })

  await knex.schema.createTableIfNotExists('notices', (t) => {
    t.increments('id').unsigned().primary()
    t.string('title', 200).notNullable()
    t.text('content', 'medium').notNullable()
    t.tinyint('isPinned').notNullable().defaultTo(0)
    t.tinyint('isActive').notNullable().defaultTo(1)
    t.integer('viewCount').unsigned().notNullable().defaultTo(0)
    t.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    t.datetime('updatedAt').notNullable().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
  })

  await knex.schema.createTableIfNotExists('inquiries', (t) => {
    t.increments('id').unsigned().primary()
    t.integer('memberId').unsigned().notNullable()
    t.tinyint('type').notNullable().comment('1:충전 2:결제 3:취소환불 4:기타')
    t.string('title', 200).notNullable()
    t.text('content').notNullable()
    t.tinyint('status').notNullable().defaultTo(0).comment('0:답변대기 1:답변완료')
    t.text('answer')
    t.datetime('answeredAt')
    t.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    t.datetime('updatedAt').notNullable().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    t.index(['memberId'], 'idx_memberId')
    t.index(['status'], 'idx_status')
  })
}

exports.down = async (knex) => {
  await knex.schema.dropTableIfExists('inquiries')
  await knex.schema.dropTableIfExists('notices')
  await knex.schema.dropTableIfExists('orders')
  await knex.schema.dropTableIfExists('products')
  await knex.schema.dropTableIfExists('password_reset_tokens')
  await knex.schema.dropTableIfExists('members')
  await knex.schema.dropTableIfExists('admin_allowed_ips')
  await knex.schema.dropTableIfExists('admins')
}
